a=int(input("Enter the A value="))
b=int(input("enter the B value="))
print("sum of value:",a+b)
print("sum of multiplication", a*b)
print("sum of subraction",a-b)
print("floor:",a//b)
print("exponential ",2**3)
print("modulus:",a%b)
print("division:",a/b)
