a=int(input("A value="))
b=int(input("B value="))
print(a==b,"::equal")
print(a<b,"::lesser than")
print(a>b,"::greater than")
print(a<=b,"::lesser than or equal")
print(a>=b,"::greater than or equal")
print(a!=b,"::not equal")